import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import 'cal-sans';
import Navbar from '@/components/base/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={cn('min-h-screen antialiased grainy font-primary')}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
